#!/bin/sh

# Using `--silent` helps for showing any errs in the first line of the response
# The first line is picked up by the VS Code GIT UI popup when rc is not 0

if npm run --silent lint:silent ; then
    exit 0
else
    npm run --silent lint:fix
    echo "❌ Prettier check failed! We ran lint:fix for you. Please add & commit again."
    exit 1
fi
